# numpy


数组跟列表
列表可以存储任意类型的而数据,数组只能存储一种数据

In [1]:
import array

In [2]:
a = array.array('i',range(10))

数据类型必须统一

In [3]:
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
import numpy as np

In [10]:
np?

`

从原有列表转换为数组


In [12]:
a_list = list(range(10))
b = np.array(a_list)
type(b)

numpy.ndarray

生成数组

In [16]:
a = np.zeros(10)
print(type(a))
# 查看数组类型
a.dtype

<class 'numpy.ndarray'>


dtype('float64')

In [20]:
a = np.zeros((4,4),dtype=int)
print(type(a))
# 查看数组类型
a.dtype
a

<class 'numpy.ndarray'>


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
a = np.zeros((4,4),dtype=float)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.full((3,3),3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [24]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros_like(a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.full_like(a,4.12,dtype=float)

array([[4.12, 4.12, 4.12, 4.12],
       [4.12, 4.12, 4.12, 4.12],
       [4.12, 4.12, 4.12, 4.12],
       [4.12, 4.12, 4.12, 4.12]])

### random


In [32]:
import random

In [38]:
print(random.randint(5,10))
print(random.random())

8
0.4213095155550386


In [40]:
np.random.random((3,3))

array([[0.67745931, 0.23116165, 0.21652319],
       [0.30806507, 0.11443597, 0.14829948],
       [0.60895704, 0.21073669, 0.94205783]])

In [41]:
# 经常用的 生成随机数
np.random.randint(0,10,(5,5))

array([[2, 2, 7, 8, 9],
       [3, 4, 9, 8, 0],
       [7, 2, 2, 3, 8],
       [2, 5, 6, 2, 1],
       [2, 9, 0, 4, 4]])

In [42]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [44]:
# 经常用到
np.linspace(0,3,100)

array([0.        , 0.03030303, 0.06060606, 0.09090909, 0.12121212,
       0.15151515, 0.18181818, 0.21212121, 0.24242424, 0.27272727,
       0.3030303 , 0.33333333, 0.36363636, 0.39393939, 0.42424242,
       0.45454545, 0.48484848, 0.51515152, 0.54545455, 0.57575758,
       0.60606061, 0.63636364, 0.66666667, 0.6969697 , 0.72727273,
       0.75757576, 0.78787879, 0.81818182, 0.84848485, 0.87878788,
       0.90909091, 0.93939394, 0.96969697, 1.        , 1.03030303,
       1.06060606, 1.09090909, 1.12121212, 1.15151515, 1.18181818,
       1.21212121, 1.24242424, 1.27272727, 1.3030303 , 1.33333333,
       1.36363636, 1.39393939, 1.42424242, 1.45454545, 1.48484848,
       1.51515152, 1.54545455, 1.57575758, 1.60606061, 1.63636364,
       1.66666667, 1.6969697 , 1.72727273, 1.75757576, 1.78787879,
       1.81818182, 1.84848485, 1.87878788, 1.90909091, 1.93939394,
       1.96969697, 2.        , 2.03030303, 2.06060606, 2.09090909,
       2.12121212, 2.15151515, 2.18181818, 2.21212121, 2.24242

In [47]:
# n维的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

|Data type  |  Description|
|:- ------|:----------------|
|bool_	 |Boolean (True or False) stored as a byte|
|int_	 |Default integer type (same as C long; normally either int64 or int32)|
|intc	 |Identical to C int (normally int32 or int64)|
|intp	 |Integer used for indexing (same as C ssize_t; normally either int32 or int64)|
|int8	 |Byte (-128 to 127)|
|int16	 |Integer (-32768 to 32767)|
|int32	 |Integer (-2147483648 to 2147483647)|
|int64	 |Integer (-9223372036854775808 to 9223372036854775807)|
|uint8	 |Unsigned integer (0 to 255)|
|uint16	 |Unsigned integer (0 to 65535)|
|uint32	 |Unsigned integer (0 to 4294967295)|
|uint64	 |Unsigned integer (0 to 18446744073709551615)|
|float_	 |Shorthand for float64|.
|float16 |Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
|float32 |Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
|float64 |Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
|complex_|Shorthand for complex128.|
|complex64	|Complex number, represented by two 32-bit floats|
|complex128	|Complex number, represented by two 64-bit floats|


访问数组元素

In [48]:
# 嵌套列表的元素访问
var = [[1,2,3],[3,4,5],[5,6,7]]
var[0][0]

1

In [57]:
# 数组元素的访问
a = np.array(var)
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [58]:
a[0]

array([1, 2, 3])

In [59]:
a[0][0]

1

In [61]:
# 等价
a[2,0],a[2][0]

(5, 5)

In [64]:
# 数组切片
a[:2,:2]

array([[1, 2],
       [3, 4]])

### 数组属性


In [65]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [68]:
#维度
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

2
(3, 3)
9
int32
4
36


### numpy数组运算

In [69]:
a = np.array(list(range(10)))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
print(a + 10)
print(a - 10)
print(a * 10)

[10 11 12 13 14 15 16 17 18 19]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
[ 0 10 20 30 40 50 60 70 80 90]


In [75]:
a=np.full((3,3),1.0,dtype=float)
a+10 #等价于 np.add(a,10)

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [76]:
a = np.linspace(0,np.pi,20)
b = np.sin(a)
print(a)
print(b)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]
[0.00000000e+00 1.64594590e-01 3.24699469e-01 4.75947393e-01
 6.14212713e-01 7.35723911e-01 8.37166478e-01 9.15773327e-01
 9.69400266e-01 9.96584493e-01 9.96584493e-01 9.69400266e-01
 9.15773327e-01 8.37166478e-01 7.35723911e-01 6.14212713e-01
 4.75947393e-01 3.24699469e-01 1.64594590e-01 1.22464680e-16]


### numpy统计类型运算

In [81]:
#求和
print(sum([1,23,3,5,3,3,5,3,5,323,5,6]))
# 数组一维求和
a = np.full(10,2.3)
print(sum(a))
# 数组多维求i和
a = np.array([[1,2],[3,4]])
print(sum(a))

# np.sum求和
np.sum(a)
np.sum(a,axis = 1)

np.max(a,axis = 1)

385
23.000000000000004
[4 6]


array([2, 4])

In [87]:
n = np.random.rand(100000)

### notebook使用技巧

%timeit 代码  
此方法来判断程序的执行效率

In [88]:
%timeit sum(n)

13.6 ms ± 283 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [89]:
%timeit np.sum(n)

41.1 µs ± 411 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 比较

In [90]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [92]:
a != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [93]:
a == a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [94]:
np.all(a>-1)

True

In [95]:
np.any(a>-1)

True

## 变形

In [96]:
a = np.full((2,10),1,dtype=float)
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [97]:
a.size

20

In [99]:
a.reshape(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [100]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [102]:
a.size

20

In [98]:
a.ndim

2


## 排序

In [103]:
l = [
    [1,2,3],
    [32,14,52],
    [22,55,65]
]
a = np.array(l)
a

array([[ 1,  2,  3],
       [32, 14, 52],
       [22, 55, 65]])

In [107]:
np.sort(a)
a.sort(axis = 0)
a

array([[ 1,  2,  3],
       [22, 14, 52],
       [32, 55, 65]])

## 拼接

In [113]:
a = np.array([1,2,3])
b = np.array([[0,2,4],[1,3,5]])

In [111]:
# 拼接
np.concatenate([a,a,a],axis=0)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [112]:
# 拼接
np.concatenate([b,b,b],axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1